name: Semgrep
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '20 00 * * *'
jobs:
  semgrep:
    uses: redcanaryco/static-analysis/.github/workflows/semgrep-reusable-workflow.yml@main
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}